import { Router } from 'express';
import * as orderController from '../controllers/orderController';
const router = Router();
router.get('/', orderController.getAllOrders);
router.get('/:id', orderController.getOrderById);
router.post('/', orderController.saveOrder);
router.delete('/:id', orderController.deleteOrder);
router.patch('/:id/status', orderController.updateOrderStatus);
router.patch('/:id/payment', orderController.updateOrderPaymentMethod);
router.put('/:id/items', orderController.updateOrderItems);
export default router;
